IS_WINDOWS_DOCKER_DESKTOP=true

APP_ID=coolify-windows-docker-desktop
APP_NAME=Coolify
APP_KEY=base64:ssTlCmrIE/q7whnKMvT6DwURikg69COzGsAwFVROm80=

DB_USERNAME=coolify
DB_PASSWORD=coolify
REDIS_PASSWORD=coolify